navbar
remihamy1/webapp pull request #23
Opened 2023-12-18 13:16 UTC by Nathan-Turlure

Refonte de la navbar

2023-12-18 13:20 UTC, xStoneSteyfer approved these changes
OK, attention au plugin d'indentation qui modifie des fichiers qui n'ont pas lieu d'être

2023-12-18 13:26 UTC, rydward requested changes
il faut que ce le bouton connexion apparaisse si l'utilisateur n'est pas connecté et inversement  déconnexion lorsque l'utilisateur est connecté

2023-12-18 13:26 UTC, akiratomi requested changes
Manque une partie de la fonctionnalité demandé (Connexion déconnexion)

2023-12-18 15:08 UTC, xStoneSteyfer approved these changes
add . fix

2023-12-19 00:02 UTC, Nathan-Turlure commented
Je viens de commit la dernière version de la navbar qui est en accord avec les changements demandé

2023-12-19 09:15 UTC, xStoneSteyfer approved these changes
OK

2023-12-19 09:16 UTC, merged